# Generated by Django 4.0.1 on 2022-04-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('c', 'Одежда'), ('u', 'Нижнее белье'), ('j', 'Бижутерия'), ('a', 'Аксессуары')], max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('items', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
    ]
