# Generated by Django 4.0.1 on 2022-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('f', 'Женский'), ('m', 'Мужской'), ('o', 'Другое'), ('no', 'Не хочу сообщать')], default='Не хочу сообщать', max_length=100),
        ),
    ]
