# Generated by Django 4.0.1 on 2022-04-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
    ]
